apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: projecta-dev
spec:
  hard:
    configmaps: "10"
    persistentvolumeclaims: "4"
    replicationcontrollers: "20"
    secrets: "10"
    services: "10"
    pods: "3"
    services.loadbalancers: "2"
